version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  style_guide = "standard"
  dialect = "typescript"
  environment = [
    "nodejs",
    "mocha",
    "mongo",
    "cypress",
    "jasmine",
    "browser",
    "jest",
    "jquery"
  ]
  plugins = [
    "react",
    "meteor",
    "angularjs",
    "vue",
    "ember",
    "angular"
  ]
